// TODO Create the conection with the server
export const clientList = {
    index: [0, 1, 2, 3, 4, 5, 6],
    title: [
        'codigo tres',
        'alertia 724',
        'jet rescue',
        'cruz roja',
        'critiq',
        'dmt',
        'gruas caba',
        // 'next store'
    ],
    logo: [
        './assets/plataforma/clientsList/codigo3-logo60.webp',
        './assets/plataforma/clientsList/alertia724-logo60.webp', 
        './assets/plataforma/clientsList/jetrescue-logo60.webp', 
        './assets/plataforma/clientsList/cruzroja-logo60.webp',
        './assets/plataforma/clientsList/critiq-logo60.webp',
        './assets/plataforma/clientsList/dmt-logo60.webp',
        './assets/plataforma/clientsList/gruascaba-logo60.webp',
        // './assets/plataforma/clientsList/next-store.jpeg',
    ],
    background: [
        './assets/plataforma/clientsList/codigo3background.webp',
        './assets/plataforma/clientsList/alertia724-background.webp',
        './assets/plataforma/clientsList/jetrescue-backgroung.webp',
        './assets/plataforma/clientsList/cruzroja-background.webp',
        './assets/plataforma/clientsList/critiq-background.webp',
        './assets/plataforma/clientsList/dmt-background.webp',
        './assets/plataforma/clientsList/gruascaba-background.webp',
        './assets/plataforma/clientsList/nextstore-background.webp',
        // 'null',
        
    ],
    url: [
        'http://www.ambulanciascodigotres.com/?fbclid=IwAR1v3KgARLQ2j1oHld7DmuF03FzZWeSck7e4yk0nnHsz9vSBjQeNhlAmjpQ',
        'null',
        'https://www.jetrescue.com.mx/',
        'https://www.cruzrojamexicana.org.mx/',
        'https://www.critiq.com.mx/',
        'https://dmt.com.mx/',
        'https://www.gruascaba.mx/',
        // 'null',
    ],
    instagram: [
        'null',
        'https://www.instagram.com/alertia724/',
        'null',
        'https://www.instagram.com/cruzroja_mx/',
        'https://www.instagram.com/critiqmx/',
        'null',
        'https://www.instagram.com/gruascaba/',
        // 'null',
    ],
    facebook: [
        'https://www.facebook.com/ambulancias.codigotres/',
        'https://www.facebook.com/AmbulanciaPrivada/',
        'https://www.facebook.com/jetrescue/',
        'https://www.facebook.com/CruzRojaMx/',
        'https://www.facebook.com/mxcritiq/',
        'https://www.facebook.com/dmt.tornillos',
        'https://www.facebook.com/gruascaba',
        // 'null',
    ],
    twitter: [
        'null',
        'null',
        'https://twitter.com/Jetrescue',
        'https://twitter.com/CruzRoja_MX',
        'null',
        'null',
        'https://twitter.com/gruascaba',
        // 'null',
    ],
    youtube: [
        'null',
        'null',
        'https://www.youtube.com/user/rescuejets',
        'https://www.youtube.com/channel/UCZEYUS1b9IoJ44SD8hK2uyw',
        'null',
        'null',
        'null',
        // 'null',
    ],
    
}

